import { Award, Globe, Users, Shield, TrendingUp, Heart, Target } from "lucide-react"

export default function About() {
  const stats = [
    { icon: Globe, value: "150+", label: "Countries Served" },
    { icon: Users, value: "60K+", label: "Active Traders" },
    { icon: Award, value: "15+", label: "Industry Awards" },
    { icon: Shield, value: "2007", label: "Founded" },
  ]
  const values = [
    { icon: Target, title: "Client First", desc: "Everything we do is designed to help our clients succeed." },
    { icon: Shield, title: "Trust & Transparency", desc: "We operate with integrity and full regulatory compliance." },
    { icon: TrendingUp, title: "Innovation", desc: "Constantly improving our technology and trading conditions." },
    { icon: Heart, title: "Community", desc: "Building a global community of successful traders." },
  ]
  return <div className="container mx-auto px-4 py-12"><div className="mb-12 text-center"><h1 className="mb-4 text-4xl font-bold">About Axi</h1><p className="mx-auto max-w-3xl text-xl text-muted-foreground">Axi is a global leader in online trading, trusted by traders since 2007. We provide access to 650+ markets with industry-leading conditions and award-winning support.</p></div><div className="mb-12 grid grid-cols-2 gap-6 lg:grid-cols-4">{stats.map((s) => <div key={s.label} className="rounded-lg border border-border bg-card p-6 text-center"><s.icon className="mx-auto mb-3 h-8 w-8 text-red-600" /><div className="text-2xl font-bold">{s.value}</div><div className="text-sm text-muted-foreground">{s.label}</div></div>)}</div><div className="mb-12 grid gap-8 md:grid-cols-2"><div className="rounded-lg border border-border bg-card p-6"><h2 className="mb-4 text-2xl font-bold">Our Story</h2><p className="mb-4 text-muted-foreground">Founded in Sydney in 2007, Axi has grown from a small Australian broker to a global trading leader serving clients in over 150 countries. We are regulated by the FCA, ASIC, FMA, and DFSA.</p><p className="text-muted-foreground">Our mission is to provide traders with the best possible trading environment — tight spreads, fast execution, and world-class support. We believe that when our clients succeed, we succeed.</p></div><div className="rounded-lg border border-border bg-card p-6"><h2 className="mb-4 text-2xl font-bold">Regulation & Licensing</h2><ul className="space-y-3 text-muted-foreground"><li className="flex items-center gap-2"><Shield className="h-4 w-4 text-green-600" /> FCA (UK) — Financial Conduct Authority</li><li className="flex items-center gap-2"><Shield className="h-4 w-4 text-green-600" /> ASIC (Australia) — Australian Securities & Investments Commission</li><li className="flex items-center gap-2"><Shield className="h-4 w-4 text-green-600" /> FMA (New Zealand) — Financial Markets Authority</li><li className="flex items-center gap-2"><Shield className="h-4 w-4 text-green-600" /> DFSA (Dubai) — Dubai Financial Services Authority</li><li className="flex items-center gap-2"><Shield className="h-4 w-4 text-green-600" /> SCB (Bahamas) — Securities Commission of The Bahamas</li></ul></div></div><div className="mb-12"><h2 className="mb-6 text-center text-2xl font-bold">Our Values</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{values.map((v) => <div key={v.title} className="rounded-lg border border-border bg-card p-5 text-center"><v.icon className="mx-auto mb-3 h-8 w-8 text-red-600" /><h3 className="mb-1 font-semibold">{v.title}</h3><p className="text-sm text-muted-foreground">{v.desc}</p></div>)}</div></div></div>
}
