import { Link } from "react-router-dom"
import { ShieldCheck, WalletCards, Users, Activity, ArrowLeft } from "lucide-react"
import { configuredCryptoNetworks } from "@/lib/crypto"
import { useAuth } from "@/lib/AuthContext"

export default function Admin() {
  const { user } = useAuth()
  const wallets = configuredCryptoNetworks()
  return <div className="container mx-auto px-4 py-10"><div className="mb-8 flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-red-600"><ShieldCheck className="h-5 w-5" /><span className="text-sm font-semibold uppercase tracking-[0.2em]">Private control room</span></div><h1 className="mt-2 text-3xl font-bold">Administration</h1><p className="mt-2 text-sm text-muted-foreground">Restricted to the configured admin allowlist. No demo transactions or fabricated user metrics are loaded.</p></div><Link to="/dashboard" className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-medium hover:bg-muted"><ArrowLeft className="h-4 w-4" /> Client area</Link></div>
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5"><Users className="h-5 w-5 text-red-600" /><p className="mt-5 text-xs text-muted-foreground">Authenticated operator</p><p className="mt-1 font-semibold truncate">{user?.email || "—"}</p></div><div className="rounded-2xl border border-border bg-card p-5"><WalletCards className="h-5 w-5 text-red-600" /><p className="mt-5 text-xs text-muted-foreground">Configured crypto wallets</p><p className="mt-1 text-2xl font-bold">{wallets.length}</p></div><div className="rounded-2xl border border-border bg-card p-5"><Activity className="h-5 w-5 text-red-600" /><p className="mt-5 text-xs text-muted-foreground">Trading execution</p><p className="mt-1 font-semibold">Integration required</p></div></div>
    <div className="mt-6 rounded-2xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">Funding configuration</h2><p className="mt-1 text-sm text-muted-foreground">Deposit addresses are read from production environment variables. Add the supplied wallet addresses before enabling funding.</p><div className="mt-5 space-y-2">{wallets.length ? wallets.map((wallet) => <div key={`${wallet.asset}-${wallet.network}`} className="flex flex-col gap-1 rounded-xl border border-border bg-muted/30 p-4 sm:flex-row sm:items-center sm:justify-between"><span className="font-semibold">{wallet.asset} · {wallet.network}</span><span className="break-all font-mono text-xs text-muted-foreground">{wallet.address}</span></div>) : <div className="rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">No wallet addresses configured yet.</div>}</div></div>
  </div>
}
