import { Link } from "react-router-dom"
import { BarChart3, CreditCard, Settings, ShieldCheck, Wallet, ArrowUpRight, ArrowDownRight } from "lucide-react"
import { useAuth } from "@/lib/AuthContext"
import LoadingSkeleton from "@/components/LoadingSkeleton"

export default function Dashboard() {
  const { user, isLoading } = useAuth()
  if (isLoading) return <LoadingSkeleton label="Loading account…" />

  return <div className="container mx-auto px-4 py-10"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-red-600">Client area</p><h1 className="mt-2 text-3xl font-bold">Welcome back, {user?.name || "Trader"}</h1><p className="mt-2 text-sm text-muted-foreground">Your account workspace is ready. Live balances and positions will populate from the connected trading service.</p></div><Link to="/settings" className="inline-flex items-center gap-2 self-start rounded-lg border border-border px-4 py-2 text-sm font-medium hover:bg-muted"><Settings className="h-4 w-4" /> Settings</Link></div>
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5"><Wallet className="h-5 w-5 text-red-600" /><p className="mt-5 text-xs text-muted-foreground">Account balance</p><p className="mt-1 text-2xl font-bold">—</p><p className="mt-1 text-xs text-muted-foreground">Waiting for live account data</p></div><div className="rounded-2xl border border-border bg-card p-5"><BarChart3 className="h-5 w-5 text-red-600" /><p className="mt-5 text-xs text-muted-foreground">Equity</p><p className="mt-1 text-2xl font-bold">—</p><p className="mt-1 text-xs text-muted-foreground">No seeded values</p></div><div className="rounded-2xl border border-border bg-card p-5"><ShieldCheck className="h-5 w-5 text-red-600" /><p className="mt-5 text-xs text-muted-foreground">Account status</p><p className="mt-1 text-2xl font-bold">Active</p><p className="mt-1 truncate text-xs text-muted-foreground">{user?.email}</p></div></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><Link to="/trading" className="group rounded-2xl border border-border bg-card p-6 hover:border-red-600/50 hover:shadow-md"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">Trading workspace</h2><p className="mt-2 text-sm text-muted-foreground">Open TradingView charts and select an instrument.</p></div><ArrowUpRight className="h-5 w-5 text-muted-foreground group-hover:text-red-600" /></div></Link><Link to="/deposit" className="group rounded-2xl border border-border bg-card p-6 hover:border-red-600/50 hover:shadow-md"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">Funding</h2><p className="mt-2 text-sm text-muted-foreground">Deposit or request a withdrawal using configured crypto addresses.</p></div><CreditCard className="h-5 w-5 text-muted-foreground group-hover:text-red-600" /></div></Link></div>
    <div className="mt-6 rounded-2xl border border-border bg-muted/30 p-6"><div className="flex items-start gap-3"><ArrowDownRight className="mt-0.5 h-5 w-5 text-muted-foreground" /><div><h2 className="font-semibold">Open positions</h2><p className="mt-1 text-sm text-muted-foreground">No positions are displayed until the production trading account is connected. This prevents demo or fabricated P&amp;L from appearing in the client area.</p></div></div></div>
  </div>
}
