import { Link } from "react-router-dom"
import { Monitor, Smartphone, Globe, BarChart3, Zap, Shield, Clock, Layers, MousePointer } from "lucide-react"

export default function MT4() {
  const features = [
    { icon: BarChart3, title: "30+ Technical Indicators", desc: "Moving averages, oscillators, and custom indicators" },
    { icon: Layers, title: "9 Timeframes", desc: "From 1 minute to monthly charts" },
    { icon: Zap, title: "Automated Trading (EAs)", desc: "Build and run expert advisors with MQL4" },
    { icon: MousePointer, title: "One-Click Trading", desc: "Execute orders instantly from the chart" },
    { icon: Shield, title: "Advanced Security", desc: "256-bit SSL encryption for all transactions" },
    { icon: Clock, title: "Real-Time Pricing", desc: "Live quotes with sub-30ms execution" },
  ]
  return <div className="container mx-auto px-4 py-12"><div className="mb-12 text-center"><h1 className="mb-4 text-4xl font-bold">MetaTrader 4</h1><p className="mx-auto max-w-2xl text-xl text-muted-foreground">The world's most popular trading platform. Simple for beginners, powerful for professionals. Trusted by millions of traders worldwide.</p></div><div className="mb-12 grid gap-8 md:grid-cols-2"><div className="rounded-lg border border-border bg-card p-6"><h2 className="mb-4 text-2xl font-bold">Download MT4</h2><p className="mb-6 text-muted-foreground">Available on all major platforms. Start trading in minutes.</p><div className="mb-4 grid grid-cols-2 gap-3"><button className="flex items-center gap-2 rounded-lg bg-muted p-3 transition-colors hover:bg-muted/80"><Monitor className="h-5 w-5" /> Windows</button><button className="flex items-center gap-2 rounded-lg bg-muted p-3 transition-colors hover:bg-muted/80"><Monitor className="h-5 w-5" /> Mac</button><button className="flex items-center gap-2 rounded-lg bg-muted p-3 transition-colors hover:bg-muted/80"><Smartphone className="h-5 w-5" /> iOS</button><button className="flex items-center gap-2 rounded-lg bg-muted p-3 transition-colors hover:bg-muted/80"><Smartphone className="h-5 w-5" /> Android</button></div><Link to="/register" className="block rounded-md bg-red-600 py-2.5 text-center font-medium text-white transition-colors hover:bg-red-700">Open Live Account</Link></div><div className="rounded-lg border border-border bg-card p-6"><h2 className="mb-4 text-2xl font-bold">MT4 WebTrader</h2><p className="mb-6 text-muted-foreground">Trade directly from your browser with no download required. Full functionality, zero installation.</p><div className="mb-4 flex items-center gap-2"><Globe className="h-5 w-5 text-red-600" /><span>Works in Chrome, Firefox, Safari, Edge</span></div><Link to="/register" className="block rounded-md border border-border py-2.5 text-center font-medium transition-colors hover:bg-muted">Launch WebTrader</Link></div></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map((f) => <div key={f.title} className="rounded-lg border border-border bg-card p-5 transition-shadow hover:shadow-md"><f.icon className="mb-3 h-8 w-8 text-red-600" /><h3 className="mb-1 font-semibold">{f.title}</h3><p className="text-sm text-muted-foreground">{f.desc}</p></div>)}</div></div>
}
