import { Link } from "react-router-dom"
import { Users, DollarSign, BarChart3, Award, ArrowRight, Globe, Handshake, Zap, Target } from "lucide-react"
import { cn } from "@/lib/utils"

export default function Partnership() {
  const programs = [
    { title: "Introducing Broker (IB)", icon: Handshake, desc: "Refer clients to Axi and earn competitive commissions on every trade they make. Perfect for educators, signal providers, and community leaders.", commission: "Up to $10 per lot", features: ["Real-time reporting", "Multi-tier commissions", "Dedicated account manager", "Marketing materials"], cta: "Become an IB", popular: true },
    { title: "Affiliate Program", icon: DollarSign, desc: "Earn CPA (Cost Per Acquisition) for every qualified trader you refer. Ideal for websites, blogs, and social media influencers.", commission: "Up to $600 CPA", features: ["High CPA payouts", "Cookie tracking", "Creative banners", "Monthly payments"], cta: "Join Affiliate", popular: false },
    { title: "Hybrid Program", icon: Zap, desc: "Combine CPA and revenue share for maximum earnings. Get paid upfront and earn ongoing commissions.", commission: "CPA + Revenue Share", features: ["Best of both worlds", "Flexible structure", "Performance bonuses", "Priority support"], cta: "Apply Now", popular: true, new: true },
    { title: "MT4 PAMM Manager", icon: BarChart3, desc: "Manage multiple client accounts from a single master account. Perfect for professional money managers.", commission: "Custom fee structure", features: ["Master account trading", "Auto allocation", "Performance fees", "Investor portal"], cta: "Learn More", popular: false },
    { title: "MT4 Multi-Account Manager", icon: Users, desc: "Trade across multiple sub-accounts simultaneously. Ideal for fund managers and professional traders.", commission: "Custom fee structure", features: ["Bulk order execution", "Real-time reporting", "Risk management tools", "Custom allocation"], cta: "Learn More", popular: false },
  ]
  const stats = [
    { icon: Globe, value: "150+", label: "Countries" },
    { icon: Users, value: "5,000+", label: "Partners" },
    { icon: DollarSign, value: "$12M+", label: "Paid in Commissions" },
    { icon: Award, value: "4.9/5", label: "Partner Rating" },
  ]
  return <div className="container mx-auto px-4 py-12"><div className="mb-12 text-center"><h1 className="mb-4 text-4xl font-bold">Partnerships</h1><p className="mx-auto max-w-2xl text-xl text-muted-foreground">Partner with Axi and earn competitive commissions. Join thousands of successful Introducing Brokers, Affiliates, and Fund Managers worldwide.</p></div><div className="mb-12 grid grid-cols-2 gap-4 lg:grid-cols-4">{stats.map((s) => <div key={s.label} className="rounded-lg border border-border bg-card p-6 text-center"><s.icon className="mx-auto mb-3 h-8 w-8 text-red-600" /><div className="text-2xl font-bold">{s.value}</div><div className="text-sm text-muted-foreground">{s.label}</div></div>)}</div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{programs.map((p) => <div key={p.title} className={cn("rounded-lg border bg-card p-6 transition-shadow hover:shadow-md", p.popular ? "border-red-600" : "border-border")}><div className="mb-4 flex items-start justify-between"><p.icon className="h-10 w-10 text-red-600" /><div className="flex gap-1">{p.new && <span className="rounded-full bg-red-600 px-2 py-0.5 text-[10px] font-bold text-white">NEW</span>}{p.popular && <span className="rounded-full bg-green-600 px-2 py-0.5 text-[10px] font-bold text-white">POPULAR</span>}</div></div><h3 className="mb-2 text-lg font-bold">{p.title}</h3><p className="mb-4 text-sm text-muted-foreground">{p.desc}</p><div className="mb-4 rounded-lg bg-muted p-3"><div className="text-xs text-muted-foreground">Commission</div><div className="text-lg font-bold text-green-600">{p.commission}</div></div><ul className="mb-6 space-y-2">{p.features.map((f) => <li key={f} className="flex items-center gap-2 text-sm text-muted-foreground"><Target className="h-3.5 w-3.5 text-green-600" /> {f}</li>)}</ul><Link to="/register" className="flex items-center justify-center gap-1 rounded-md bg-red-600 py-2.5 text-center font-medium text-white transition-colors hover:bg-red-700">{p.cta} <ArrowRight className="h-4 w-4" /></Link></div>)}</div><div className="mt-12 rounded-lg bg-slate-950 p-8 text-center text-white"><h2 className="mb-3 text-2xl font-bold">Ready to Partner with Axi?</h2><p className="mx-auto mb-6 max-w-xl text-slate-400">Join our partnership program today and start earning. Our dedicated partnership team is here to help you succeed.</p><div className="flex justify-center gap-3"><Link to="/register" className="rounded-md bg-red-600 px-6 py-2.5 font-medium hover:bg-red-700">Apply Now</Link><a href="mailto:partners@axi.com" className="rounded-md bg-white/10 px-6 py-2.5 font-medium hover:bg-white/20">Contact Team</a></div></div></div>
}
