import { Link } from "react-router-dom"
import { ShieldCheck, Settings, UserRound } from "lucide-react"
import { useAuth } from "@/lib/AuthContext"

export default function Profile() {
  const { user } = useAuth()
  const kyc = localStorage.getItem("axi_kyc_status") || "not_started"
  return <div className="container mx-auto max-w-4xl px-4 py-10"><div className="mb-8 flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-[#d71920] text-2xl font-bold text-white">{(user?.name || "T").charAt(0).toUpperCase()}</div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-red-600">Profile</p><h1 className="text-3xl font-bold">{user?.name || "Trader"}</h1><p className="text-sm text-muted-foreground">{user?.email}</p></div></div><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-6"><UserRound className="h-5 w-5 text-red-600" /><h2 className="mt-4 font-semibold">Personal information</h2><div className="mt-5 space-y-4"><div><p className="text-xs text-muted-foreground">Full name</p><p className="mt-1 font-medium">{user?.name || "—"}</p></div><div><p className="text-xs text-muted-foreground">Email</p><p className="mt-1 font-medium break-all">{user?.email || "—"}</p></div></div></div><div className="rounded-2xl border border-border bg-card p-6"><ShieldCheck className="h-5 w-5 text-red-600" /><h2 className="mt-4 font-semibold">Identity verification</h2><p className="mt-2 text-sm text-muted-foreground">KYC status controls access to regulated account functions.</p><div className="mt-5 rounded-xl bg-muted p-4"><span className="text-sm font-semibold capitalize">{kyc.replace("_", " ")}</span></div><Link to="/kyc" className="mt-4 inline-flex w-full items-center justify-center rounded-lg bg-[#d71920] px-4 py-2.5 text-sm font-semibold text-white">Manage verification</Link></div></div><Link to="/settings" className="mt-5 inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-medium hover:bg-muted"><Settings className="h-4 w-4" /> Account settings</Link></div>
}
