import { useState } from "react"
import { Bell, Lock, User, Globe, Moon, Sun, Shield, Save, Eye, EyeOff } from "lucide-react"
import { cn } from "@/lib/utils"
import { toast } from "@/components/ui/toaster"
import { useAuth } from "@/lib/AuthContext"
import { useTheme } from "@/lib/ThemeContext"

export default function Settings() {
  const [tab, setTab] = useState("profile")
  const [showCurrent, setShowCurrent] = useState(false)
  const [showNew, setShowNew] = useState(false)
  const [showConfirm, setShowConfirm] = useState(false)
  const { user } = useAuth()
  const { theme, setTheme } = useTheme()
  const tabs = [{ key: "profile", label: "Profile", icon: User }, { key: "security", label: "Security", icon: Lock }, { key: "notifications", label: "Notifications", icon: Bell }, { key: "preferences", label: "Preferences", icon: Globe }]

  return <div className="container mx-auto max-w-5xl px-4 py-10"><div className="mb-7"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-red-600">Account</p><h1 className="mt-2 text-3xl font-bold">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage your account preferences without seeded personal data.</p></div><div className="grid gap-6 md:grid-cols-[220px_1fr]"><div className="space-y-1">{tabs.map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={cn("flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-sm font-medium", tab === item.key ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted")}><item.icon className="h-4 w-4" />{item.label}</button>)}</div><div className="rounded-2xl border border-border bg-card p-6">
    {tab === "profile" && <div className="space-y-5"><h2 className="text-lg font-semibold">Profile information</h2><div><label className="text-sm font-medium">Name</label><input value={user?.name || ""} readOnly className="mt-1.5 h-11 w-full rounded-lg border border-input bg-muted px-3 text-sm" /></div><div><label className="text-sm font-medium">Email</label><input value={user?.email || ""} readOnly className="mt-1.5 h-11 w-full rounded-lg border border-input bg-muted px-3 text-sm" /></div><div className="rounded-xl border border-border bg-muted/40 p-4 text-sm text-muted-foreground">Additional personal information can be enabled when the production account profile API is connected.</div></div>}
    {tab === "security" && <div className="space-y-5"><h2 className="text-lg font-semibold">Security</h2><div className="flex items-center gap-3 rounded-xl border border-green-200 bg-green-50 p-4 dark:border-green-900/40 dark:bg-green-950/20"><Shield className="h-5 w-5 text-green-600" /><div><p className="text-sm font-semibold">Protected session</p><p className="text-xs text-muted-foreground">Your active client session is stored locally for this frontend.</p></div></div>{[{label:"Current password",show:showCurrent,set:setShowCurrent},{label:"New password",show:showNew,set:setShowNew},{label:"Confirm new password",show:showConfirm,set:setShowConfirm}].map((field) => <div key={field.label}><label className="text-sm font-medium">{field.label}</label><div className="relative mt-1.5"><input type={field.show ? "text" : "password"} className="h-11 w-full rounded-lg border border-input bg-background px-3 pr-11 outline-none focus:ring-2 focus:ring-ring" /><button type="button" onClick={() => field.set(!field.show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">{field.show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div>)}</div>}
    {tab === "notifications" && <div className="space-y-5"><h2 className="text-lg font-semibold">Notification preferences</h2>{["Price alerts","Trade execution updates","Funding updates","Security alerts","Product updates"].map((label) => <label key={label} className="flex items-center justify-between border-b border-border py-3 last:border-0"><span className="text-sm font-medium">{label}</span><input type="checkbox" className="h-4 w-4 accent-red-600" /></label>)}</div>}
    {tab === "preferences" && <div className="space-y-5"><h2 className="text-lg font-semibold">Preferences</h2><div className="flex items-center justify-between rounded-xl bg-muted p-4"><div className="flex items-center gap-3">{theme === "dark" ? <Moon className="h-5 w-5" /> : <Sun className="h-5 w-5" />}<div><p className="text-sm font-semibold">Theme</p><p className="text-xs text-muted-foreground">Switch between dark and white themes.</p></div></div><div className="flex gap-1 rounded-lg border border-border bg-background p-1"><button onClick={() => setTheme("light")} className={cn("rounded-md px-3 py-1.5 text-xs font-semibold", theme === "light" && "bg-muted")}>White</button><button onClick={() => setTheme("dark")} className={cn("rounded-md px-3 py-1.5 text-xs font-semibold", theme === "dark" && "bg-muted")}>Dark</button></div></div><div><label className="text-sm font-medium">Language</label><select className="mt-1.5 h-11 w-full rounded-lg border border-input bg-background px-3"><option>English</option></select></div><div><label className="text-sm font-medium">Timezone</label><select className="mt-1.5 h-11 w-full rounded-lg border border-input bg-background px-3"><option>Browser timezone</option></select></div></div>}
    <div className="mt-8 border-t border-border pt-5"><button onClick={() => toast("Settings saved", "success")} className="flex items-center gap-2 rounded-lg bg-[#d71920] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#b9141a]"><Save className="h-4 w-4" /> Save Changes</button></div>
  </div></div></div>
}
