import { LockKeyhole, ArrowUp, ArrowDown } from "lucide-react"
import { cn } from "@/lib/utils"
import type { Instrument } from "@/types"

export default function OrderPanel({ instrument }: { instrument?: Instrument }) {
  if (!instrument) return <div className="grid h-full place-items-center rounded-xl border border-border bg-card text-sm text-muted-foreground">Select an instrument</div>

  return <div className="flex h-full flex-col overflow-hidden rounded-xl border border-border bg-card"><div className="border-b border-border p-4"><p className="text-xs font-medium text-muted-foreground">Trading ticket</p><h2 className="mt-1 text-lg font-bold">{instrument.symbol}</h2><p className="text-xs text-muted-foreground">{instrument.name}</p></div><div className="flex-1 space-y-5 p-4"><div className="rounded-xl bg-muted p-4"><p className="text-sm font-semibold">Live execution connection</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Order routing is intentionally not simulated. Connect the production trading API before enabling order submission.</p></div><div className="grid grid-cols-2 gap-2"><button disabled className="flex items-center justify-center gap-2 rounded-lg bg-green-600/30 py-3 text-sm font-bold text-green-700 opacity-70 dark:text-green-300"><ArrowUp className="h-4 w-4" /> Buy</button><button disabled className="flex items-center justify-center gap-2 rounded-lg bg-red-600/20 py-3 text-sm font-bold text-red-700 opacity-70 dark:text-red-300"><ArrowDown className="h-4 w-4" /> Sell</button></div><div className="space-y-3"><div><label className="text-xs font-medium text-muted-foreground">Volume</label><div className="mt-1 h-10 rounded-md border border-input bg-muted px-3 py-2 text-sm text-muted-foreground">Awaiting account connection</div></div><div><label className="text-xs font-medium text-muted-foreground">Risk controls</label><div className="mt-1 grid grid-cols-2 gap-2"><div className="h-10 rounded-md border border-input bg-muted px-3 py-2 text-xs text-muted-foreground">Stop loss</div><div className="h-10 rounded-md border border-input bg-muted px-3 py-2 text-xs text-muted-foreground">Take profit</div></div></div></div></div><div className="border-t border-border p-4"><div className="flex items-center gap-2 rounded-lg border border-border bg-muted/50 p-3 text-xs text-muted-foreground"><LockKeyhole className="h-4 w-4 shrink-0" /> Trading actions stay disabled until a real execution service is connected.</div></div></div>
}
